spring:
  main:
    web-application-type: none


embabel:

  dice:
    source-analyzer:
      # Multiple LLMs run in parallel with agreement voting
      llms:
        #        - model: gpt-4.1
        #        - model: claude-sonnet-4-5
        - model: gpt-4.1-mini
        - model: claude-haiku-4-5

      # Minimum LLMs that must agree (only applies with multiple LLMs)
      min-agreement: 1

  agent:
    logging:
      personality: severance

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){magenta} %clr(%-5level) %clr(%logger{0}){cyan} %clr(-){faint} %msg%n"
  level:
    com.embabel.agent.core.ActionRunner: DEBUG
    com.embabel.agent.config.models.DockerLocalModels: DEBUG
    com.embabel.agent.web.sse.SSEController: INFO
    com.embabel.agent.tools.mcp: DEBUG
